name: Mirroring

on:
  push:
    branches:  [master]
  workflow_dispatch:

jobs:
  to_gitlab:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0
      env: 
        token: ${{ secrets.GITLAB_ACCESS_TOKEN }}  
    - name: Push To Gitlab
      run: |
        echo Starting to push repo to gitlab
        git config user.name "githubBot"
        git config user.email "githubBot@users.noreply.github.com"
        git remote add gitlab "https://githubBot:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.probesys.com/troizaire/ootemplate.git"
        git fetch --all        
        git push --force gitlab master:master
