name: Unittest

on:
  [push, workflow_dispatch]

jobs:
  lotemplate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build image
      run: docker compose build

    - name: chown
      run: chmod a+rwX -R .

    - name: test
      run: make tests
